matrix:
  include:
    - language: python
      install:
        - pip install tox
      script:
        - tox
      env:
        - TOXENV=bashate

    - language: shell
      script:
        - bash -c 'shopt -s globstar; shellcheck **/*.sh'
