---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
data:
  envoy.yaml: |
    static_resources:
      listeners:
      - address:
          socket_address:
            address: 0.0.0.0
            port_value: 9000
        filter_chains:
          filters:
          - name: envoy.http_connection_manager
            config:
              codec_type: auto
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains:
                  - "*"
                  routes:
                  - match:
                      prefix: "/"
                    route:
                      cluster: local_service
              http_filters:
              - name: envoy.router
      clusters:
      - name: local_service
        connect_timeout: 0.25s
        type: STATIC
        lb_policy: round_robin
        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 80
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 82
      targetPort: 9000
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: website
          image: nginx:1.19.0
          resources:
            limits:
              cpu: .1
              memory: 256Mi
        - name: sidecar
          image: envoyproxy/envoy:v1.14.1
          resources:
            limits:
              cpu: .1
              memory: 256Mi
          volumeMounts:
            - name: config
              mountPath: /etc/envoy/
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: envoy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
data:
  config: |
    import http from "k6/http";
    import { check, sleep } from "k6";

    export let options = {
      vus: 50,
      duration: "4m"
    };

    export default function() {
      let res = http.get("http://nginx.default.svc.cluster.local:82");
      check(res, {
        "status was 200": (r) => r.status == 200,
        "transaction time OK": (r) => r.timings.duration < 200
      });
    };
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: k6-test
              image: loadimpact/k6
              command: ["k6", "run", "--out", "influxdb=http://metrics-db-influxdb.default.svc.cluster.local:8086", "/opt/script.js"]
              volumeMounts:
                - name: k6-volume
                  mountPath: /opt/
          volumes:
            - name: k6-volume
              configMap:
                name: k6-config
                items:
                  - key: config
                    path: script.js
          restartPolicy: OnFailure
