apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: ClusterIP
  ports:
    - port: 82
      targetPort: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-config
data:
  config: |
    import http from "k6/http";
    import { check, sleep } from "k6";

    export let options = {
      vus: 500,
      duration: "4m"
    };

    export default function() {
      let res = http.get("http://nginx.default.svc.cluster.local:82");
      check(res, {
        "status was 200": (r) => r.status == 200,
        "transaction time OK": (r) => r.timings.duration < 200
      });
      sleep(1);
    };
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: k6-cron
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k6-test
            image: loadimpact/k6
            command: [ "k6", "run", "--out", "influxdb=http://metrics-db-influxdb.default.svc.cluster.local:8086", "/opt/script.js" ]
            volumeMounts:
            - name: k6-volume
              mountPath: /opt/
          volumes:
            - name: k6-volume
              configMap:
                name: k6-config
                items:
                  - key: config
                    path: script.js
          restartPolicy: OnFailure
